// UI language strings for Smart Campus Navigator

const LANG = {
  en: {
    appTitle: 'Smart Campus Navigator',
    searchPlaceholder: 'Search campus locations…',
    sidebarTitle: 'Location details',
    sidebarSubtitle: 'Dr. B. R. Ambedkar Polytechnic College, Gwalior',
    sidebarDefault: 'Click a location pin on the map to see details here.',
    adminButton: 'Admin',
    languageToggle: 'EN / HI',
    floorLabel: 'Floor',
    blockLabel: 'Block',
    categoryLabel: 'Category',
    noResults: 'No matching locations found.',
    categories: {
      academic: 'Academic',
      lab: 'Laboratory',
      admin: 'Administration',
      library: 'Library',
      canteen: 'Canteen',
      hostel: 'Hostel',
      sports: 'Sports',
      parking: 'Parking',
      washroom: 'Washroom',
      washroom_girls: 'Girls Washroom',
    },
  },
  hi: {
    appTitle: 'स्मार्ट कैंपस नेविगेटर',
    searchPlaceholder: 'कैंपस स्थान खोजें…',
    sidebarTitle: 'स्थान विवरण',
    sidebarSubtitle: 'डा. भीमराव आंबेडकर पॉलिटेक्निक महाविद्यालय, ग्वालियर',
    sidebarDefault: 'विवरण देखने के लिए मानचित्र पर किसी स्थान पिन पर क्लिक करें।',
    adminButton: 'प्रशासन',
    languageToggle: 'अंग्रेज़ी / हिंदी',
    floorLabel: 'मंज़िल',
    blockLabel: 'ब्लॉक',
    categoryLabel: 'श्रेणी',
    noResults: 'कोई मिलते-जुलते स्थान नहीं मिले।',
    categories: {
      academic: 'शैक्षणिक',
      lab: 'प्रयोगशाला',
      admin: 'प्रशासन',
      library: 'पुस्तकालय',
      canteen: 'कैंटीन',
      hostel: 'छात्रावास',
      sports: 'खेल',
      parking: 'पार्किंग',
      washroom: 'शौचालय',
      washroom_girls: 'छात्राओं का शौचालय',
    },
  },
};

